### ISSUE TITLE
Problem with Multi-Column Primary Key in MySQL

### ISSUE THREAD

**Issue by kanocz** [mijia/modelq#12]
In case when table has multi-column primary key (also if table hase only one unique key and it's multi-column mysql shows it as primary) only one of fields of this index is marked as primary and this breaks generated functions like updating record in database.

**Comment by mijia** [comment]
Yeah, this is a design problem, I will think about this, :)

**Comment by mijia** [comment]
Hi @kanocz ,

I have committed the fix for multi-column primary keys, maybe you can help to check out.
Thank you very much and sorry for so late to fix this.

**Comment by kanocz** [comment]
Thank you very much! Works as expected
