### ISSUE TITLE
Joins

### ISSUE THREAD

**Issue by joeblew99** [mijia/modelq#16]
It often is such that you can create struts in go that are a merge on one of more tables. These are sometimes called datasets, because they are a set of tables.

Then to fill the dataset, you can call the crud for each table  manually doing the joins.

I did this before in c# and it worked OK.
I think we had a dB with almost 1,000 tables, and so this simple technique removed lots of boring coding.

It also properly separates for middler tier / client types from you database types.

The only real work is to write data transformation code that maps your database types to and from you datset types.

For many use cases of just managing simple things in the dB you don't need to use dataset types still. For example a user table. Then just the crud is fine.

The dataset types can be generated using protocol buffers or flat buffers. I prefer protocol buffers because it also generates the service calls also.

Then you have code generated a hell of alot of the boring code.

Just an idea !!

**Comment by mijia** [comment]
@joeblew99 Sounds very interesting, I will definitely consider this, thank you very much for the help.

**Comment by joeblew99** [comment]
http://blog.ralch.com/tutorial/golang-query-data-with-linq/

This is perfect way to do it quickly.
Uses reflection, so slowish. But quite easy to do the data transformation between the dataset types and the database types

**Comment by mijia** [comment]
@joeblew99 Not using reflection is the main reason to have this code generator, :)

**Comment by joeblew99** [comment]
Ok I know what you mean.

How stable is the code now ? Am thinking of using on a project. 
I assume it does not support stored procedures.

**Comment by mijia** [comment]
@joeblew99 we are using this on some projects inside our team. It's good so far when there is no complicated SQL queries. And we use sqlx for the complicated sqls, the interfaces are the same so you can open a database with the sqlx, make "static" query with modelq, make complicated query with sqlx.

No, it does not support stored procedures, :(

**Comment by joeblew99** [comment]
That's a good point. Can always use a standard SQL.


 The other biggy is Gorm. I will try both and see
