### ISSUE TITLE
Support your own queries (for custom things like full text queries)

### ISSUE THREAD

**Issue by sinni800** [mijia/modelq#19]
Well... We could do that easily if we had access to functionality like the "toType" function, the one that takes `(columns []gmq.Column, rb []sql.RawBytes)`. It just does the hard work for you.

There has to be some way to do outlandish queries onto a type, having modelq trust you that you're returning the right columns to it. Even if it's just a `blaobjs.Query("query here")` that returns a `_BlaQuery` so you can start outputting results. It doesn't have to support any more Filters or anything.

**Comment by Gys** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  greulen@gmail.com
    Domain reulen.nl has exceeded the max emails per hour (10/5 (200%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-ob0-f171.google.com ([209.85.214.171]:35794)
	by fyvie.footholds.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <greulen+caf_=gijs=reulen.nl@gmail.com>)
	id 1alcsO-0007pp-UW
	for gijs@reulen.nl; Thu, 31 Mar 2016 14:43:09 +0100
Received: by mail-ob0-f171.google.com with SMTP id fp4so23195882obb.2
        for <gijs@reulen.nl>; Thu, 31 Mar 2016 06:42:49 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:message-id:subject:mime-version:content-transfer-encoding
         :precedence:list-id:list-archive:list-post:list-unsubscribe;
        bh=N4z9LGKfCTZQ3inUZJmsAG79yicpRBzUTI4MVe0RQHo=;
        b=cF+VKnNcM5VwgrTAwCAPGZFzAe+1aSPbsD+gU7P/uMDYNa4R5ppboO98o+On3/r8XT
         5AZGqEgaEig2THJ7QlSznziDaNDtLXqmBTC5xl6/CHx3bjdCOq3l0UwBT+eENr0Ie+94
         huox/tZP4UtvhztXPWWHUZJjYjaiTgyuUh/7nl4+hIDLmrYLJXGu2SuwP5tEauylS1Ay
         +sHhLy26GMTNoddEPRjoy4ygwVIDzKZEMCutdZuyegHPd13LzTBM7x3ou1ByyCjAz9AU
         Gs4RUdFudCdNKwASpvwNBHNeN9KvNNid8Q0aY0C53dcutRbTA2WNrcZJPI2KhBpuJPjv
         p0IA==
X-Gm-Message-State: AD7BkJJMlXWAexDU6LGtkP+t7+yAYTx2EbIIQqsWi1ZFk0q8B44B/PJYAsQb6BAj8jYJHrunrIhiiHSIma6DwZo9GSFIvn4=
X-Received: by 10.182.165.67 with SMTP id yw3mr8192134obb.45.1459431748260;
        Thu, 31 Mar 2016 06:42:28 -0700 (PDT)
X-Forwarded-To: gijs@reulen.nl
X-Forwarded-For: greulen@gmail.com gijs@reulen.nl
Delivered-To: greulen@gmail.com
Received: by 10.157.13.231 with SMTP id 94csp131213ots;
        Thu, 31 Mar 2016 06:42:27 -0700 (PDT)
X-Received: by 10.55.77.206 with SMTP id a197mr16221039qkb.43.1459431747197;
        Thu, 31 Mar 2016 06:42:27 -0700 (PDT)
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2-ext3.iad.github.net. [192.30.252.194])
        by mx.google.com with ESMTPS id g131si7775684qhd.79.2016.03.31.06.42.27
        for <greulen@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 31 Mar 2016 06:42:27 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) client-ip=192.30.252.194;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE dis=NONE) header.from=github.com
Date: Thu, 31 Mar 2016 06:42:26 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1459431746;
	bh=N4z9LGKfCTZQ3inUZJmsAG79yicpRBzUTI4MVe0RQHo=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=CrlkOD74XMmPtDsn+/ctgpPwAS7AOSNLsXp1SZ7Z0e6TQUPX6BJmWoBBnQRt7yiwb
	 U/uFmGMkH5NhElMYIFOo4pmgZQiQG9WWbJaDsrtDn54gvk+JPoQ+ILE/FRjAsSZ4ll
	 0JLBB9C9J+qwrgDuDAyiCup4Ex1pW7beLcoazL88=

**Comment by kanocz** [comment]
You can easily use custom template for generation code and add this functionality

**Comment by Gys** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  greulen@gmail.com
    Domain reulen.nl has exceeded the max emails per hour (11/5 (220%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-ob0-f181.google.com ([209.85.214.181]:36727)
	by fyvie.footholds.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <greulen+caf_=gijs=reulen.nl@gmail.com>)
	id 1alcvk-00017y-El
	for gijs@reulen.nl; Thu, 31 Mar 2016 14:46:36 +0100
Received: by mail-ob0-f181.google.com with SMTP id m7so27097843obh.3
        for <gijs@reulen.nl>; Thu, 31 Mar 2016 06:46:16 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=DMO6KAVJV/hXZmmk17hBK80XP4k9sv31FhhhJjAWX6o=;
        b=HRaTWmpXXlwnU5c2/GH0vZPzYSsBGZNHdSsTQuLKZMwVrMZkLKBp8IzrNSgaLDuG2D
         OgcR/Jyx+rEFJ3AYHaxOIt5ZuXWXX6RiR/dIp/YyuhbM7SyEDtyH3FncmPfoiv1g3s9x
         1/NEAKcLNphvZQbJhHstAUHbxQcz7Bt+PMJjvbSNrlUGy96Kj50JWG0cKgnGibHKiiFe
         aZZB61h6mjaLlFQvDBBnPqQolJd9KqQX8taPIb/4HRLf1Ufy4alhDPfV5DSx+/ZyOuTZ
         liL9QLaSlaoUDPs50DL3F6jM3TdxmNIQTNVLLNM2D7chARif7a40p+pMLJYBebVv8Vp1
         YHjg==
X-Gm-Message-State: AD7BkJLP5Ej3pvdW4QZUr7CrI+LclUNrUjXaHTGx4iyxx5238AIyV7CRqxmkXhI8VjtfRR7gQXKZ8WxOt/whP2WSxVkYQgk=
X-Received: by 10.182.142.169 with SMTP id rx9mr8384321obb.34.1459431955804;
        Thu, 31 Mar 2016 06:45:55 -0700 (PDT)
X-Forwarded-To: gijs@reulen.nl
X-Forwarded-For: greulen@gmail.com gijs@reulen.nl
Delivered-To: greulen@gmail.com
Received: by 10.157.13.231 with SMTP id 94csp132884ots;
        Thu, 31 Mar 2016 06:45:55 -0700 (PDT)
X-Received: by 10.107.151.74 with SMTP id z71mr18269516iod.43.1459431955111;
        Thu, 31 Mar 2016 06:45:55 -0700 (PDT)
Received: from o4.sgmail.github.com (o4.sgmail.github.com. [192.254.112.99])
        by mx.google.com with ESMTPS id 98si7502222iok.122.2016.03.31.06.45.54
        for <greulen@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 31 Mar 2016 06:45:55 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of bounces+848413-185c-greulen=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) client-ip=192.254.112.99;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com;
       dkim=pass header.i=@sendgrid.info;
       spf=pass (google.com: best guess record for domain of bounces+848413-185c-greulen=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) smtp.mailfrom=bounces+848413-185c-greulen=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=W62uiORgNCgTETsaLWai+TS1U2E=; b=jMuxiQyLCnawcp9f
	ZBcNuYvWwdQUWCy6cTA2XfrxyoEq+2bT7/hT5CrRkqfXAEyi41EeMZGzxVv4ug8I
	G9t9bvSMnXBNKU3eIMx/k3dVqntIJ88mAMqJP49TE1eoMVeR1cy7lsytv+Pk5jE+
	kzSQ+PXL0/ZXzh71tBR8kmfCCE8=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=W62uiORgNCgTETsaLWai+TS1U2E=; b=jedjEwC2h0R4Eb5h/Y
	eeu4X+tV6yJYjwGlZLoYQ7GZm2jaf7YGtIIfEZfZInTGcUil2+Ij8+XnUqUmWHHE
	dALZXPeyDsJiJ4yRFS6khmuyDvev/H1cEGTiKNfHO4HEYGpaoW44alu2EJyvSFta
	i+VTn1NguSU7Zd7cEFE3RUd8s=
Received: by filter0604p1mdw1.sendgrid.net with SMTP id filter0604p1mdw1.10145.56FD2A103C
        2016-03-31 13:45:52.961317862 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id nr-xHgidRiu3wy33-3Kx9A
	for <greulen@gmail.com>; Thu, 31 Mar 2016 13:45:52.626 +0000 (UTC)
Date: Thu, 31 Mar 2016 06:45:52 -0700

**Comment by sinni800** [comment]
Easily? Selecting uses the `gmq.Select` function to create a query object... And on the gmq side there's also no function to create a query object strictly from a query string. 

On the other hand, maybe not even using the Query type will be the better route... But that means duplicating all the functionality related to getting the data from the query.

**Comment by Gys** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  greulen@gmail.com
    Domain reulen.nl has exceeded the max emails per hour (16/5 (320%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-ob0-f179.google.com ([209.85.214.179]:35333)
	by fyvie.footholds.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <greulen+caf_=gijs=reulen.nl@gmail.com>)
	id 1ald8V-00083s-Eh
	for gijs@reulen.nl; Thu, 31 Mar 2016 14:59:47 +0100
Received: by mail-ob0-f179.google.com with SMTP id fp4so23549547obb.2
        for <gijs@reulen.nl>; Thu, 31 Mar 2016 06:59:27 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=z6022gQ7XUvI5q0SSqJ+7zp2Pj/r8o6T4SEhYYDOyjA=;
        b=mewq4eTq98za39vibebrNrc2k032iN/gN8S9pOdI3bhlI+3Y6FCoDKlr+Nd2Mgvn6Q
         x/EbrNA/dih6LDI3ldlcXlL4btc0EXpE9eA4RND1XEbx5ADV35fiXTt8PjqeS8aOEIUb
         kOGoyU8tmNFu/986hRvpQYrg7+zhCJs5m88swqwIFCae4FnTonIGK48+kSeZyj2b+Dg/
         oNkXkYZeW17YRBCKc9FdcWQMaqfQipc9OCbiJMtlGW/kXy2c9P9lU14kpOf5CficP1B8
         TBbKAEP4pZtTmgZBAQYXwwVzQAMJ/zzDxCsIP29dJrEA+4CC3EydUQ+xyOw8HwAflgA7
         bXlg==
X-Gm-Message-State: AD7BkJLVNs0E4VCY1LtPENFm/5eNbY/WmL3VSIlrQ4iqUE6HPeh0/VqxDOZkaFYSHis0LmkmK8kOaU8u1lV8qiJEkBFPrSE=
X-Received: by 10.60.155.97 with SMTP id vv1mr8358903oeb.60.1459432746582;
        Thu, 31 Mar 2016 06:59:06 -0700 (PDT)
X-Forwarded-To: gijs@reulen.nl
X-Forwarded-For: greulen@gmail.com gijs@reulen.nl
Delivered-To: greulen@gmail.com
Received: by 10.157.13.231 with SMTP id 94csp139060ots;
        Thu, 31 Mar 2016 06:59:05 -0700 (PDT)
X-Received: by 10.107.36.80 with SMTP id k77mr15388749iok.121.1459432745920;
        Thu, 31 Mar 2016 06:59:05 -0700 (PDT)
Received: from o3.sgmail.github.com (o3.sgmail.github.com. [192.254.112.98])
        by mx.google.com with ESMTPS id a13si11153056igm.79.2016.03.31.06.59.05
        for <greulen@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 31 Mar 2016 06:59:05 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of bounces+848413-185c-greulen=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) client-ip=192.254.112.98;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com;
       dkim=pass header.i=@sendgrid.info;
       spf=pass (google.com: best guess record for domain of bounces+848413-185c-greulen=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-185c-greulen=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YI8+RWpDfH8e+RBapiyT1yCEXWU=; b=q6UdJ0HROGbRTkbG
	JM/8vZ3DcM/znObZ553zqRU1QyZvAOrAi0uWTtne+gPkhJV3bJN4bm7vBfcVGmkJ
	UDIYAEAkgb8vZao9lT/AL3sYlgxNa5GuSAgrM8etCVJj8TABYROS1joSyXDFmss1
	LckgV2EY8sg75YtXmHRiQbhMZiY=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=YI8+RWpDfH8e+RBapiyT1yCEXWU=; b=G0hjdNrrt6G9ZaxGUG
	z/T2TaMkvW0BsGC5JHMRB+qIX288a2PQeOezNPkOqYh76on//N+OGzycvcOqi550
	w+v01c9gkAyVDl3sx6eaoZJ27pli+vNOR7doH4MwewM0UIVu5H1XIhYcKJcTZmu3
	d6/9SHHrsdCvi76L1Gl+vaHtI=
Received: by filter0490p1mdw1.sendgrid.net with SMTP id filter0490p1mdw1.21672.56FD2D282D
        2016-03-31 13:59:04.328414798 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id bS1e_MOmRfy2eQFrXAs-Dw
	for <greulen@gmail.com>; Thu, 31 Mar 2016 13:59:03.317 +0000 (UTC)
Date: Thu, 31 Mar 2016 06:59:03 -0700

**Comment by kanocz** [comment]
I mean do you really need to use gmq part? using custom template (one is in exmaple folder) you can customize code generation and optimize result. Or you can extract original template from templates.go and add what do you need

**Comment by sinni800** [comment]
I don't really have any idea right now how I would do it. That's why I am asking for this. I was also suspecting since the library is pretty limited right now (things like COUNT don't work) that others would be interested in this feature.

**Comment by mijia** [comment]
@sinni800 Hi, I am really confused about what you are asking for, can you provide me some more specific examples or what kind of code you would be likely to be writing? 

If you still want to write SQL statements like what you can do with sqlx, you can just use modelq to generate the sqlx compatible structs without anything related to the gmq (using custom templates). Will this solve your problem?

**Comment by sinni800** [comment]
Actually, yeah. I would just write all my queries myself then and use sqlx to apply them to structs instead of modelq...

That would work out.

**Comment by mijia** [comment]
I will close this then. Thank you very much.
