### ISSUE TITLE
Prepared statements should close

### ISSUE THREAD

**Issue by richhx** [mijia/modelq#32]
Prepare statements are leaking whenever an UPDATE is made. The statements are getting closed for queries `(q _Query) query(...)`but not for any updates made `(q _Query) exec(...)` see `modelq/gmq/package.go`. The prepares get deallocated whenever the connection disappears, but in the case that the connection persists and many updates are being done via transactions, we will eventually hit the maximum number of prepared statements (which by default is [13682](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_prepared_stmt_count)) and receive [error 1461](https://support.oracle.com/knowledge/Middleware/2239331_1.html). This shouldn't happen. A workaround would be to increase the limit, but the preferred way would be to close the statement when it's finished.

https://dev.mysql.com/doc/refman/5.7/en/server-status-variables.html#statvar_Prepared_stmt_count

**Comment by mijia** [comment]
Thank you very much. The PR has been merged.
