### ISSUE TITLE
Consideration of Slick code base for some of the complex join tasks

### ISSUE THREAD

**Issue by rdelossantos** [mijia/modelq#4]
Hello Mijia:

This code generator looks amazing at it's early stage, so please keep working and i hope it could be something powerful like the Scala Slick Code generator and Framework. I'm in my baby steps for GOLANG, so i'm learning a lot from your clever code. **I would like to know if you can release the code with an MIT license and add it to the project**, i'll keep watching :).

Rayner

**Comment by mijia** [comment]
@rdelossantos Sorry for missing the license information, have added it.
The title is really a great advice, I indeed got the inspiration from Slick, will take a deep look into it.
Thank you very much, :)
