### ISSUE TITLE
Generalize template generation

### ISSUE THREAD

**Issue by tarqe39** [mijia/modelq#6]
Hi, first of all, nice job. I had the exact same idea for this :) Its great to be able to scaffold repositories for data manipulation, since its quite repetative task and prone to errors.
Just a tought - would it be possible to do something like adding a switch to CLI to use custom templates? I think you can use {{define XXX}} to declare fragments, so parsing one file with all the fragments needed and using them instead of deafults for code generation shouldn't be a overkill.
It would add a great flexibility to the lib. I can help of course ;)

**Comment by mijia** [comment]
@tarqe39 Hi, thank you very much for your interest. Would you like to provide a more detail example for this? :)

**Comment by tarqe39** [comment]
I need to use sqlx, custom context and so on, so gmq will not work for me.
It would be nice if i could define my own template with sections /fragments that correspond to your templates(in templates.go). The tool would then generate code from my templates.

**Comment by mijia** [comment]
@tarqe39 Ah, got you, would you like to provide me a sample of the target code or the template so I can generalize this feature? Thank you very much.

**Comment by tarqe39** [comment]
content of template doesnt matter, it can be anything. idea is to load file with multiple sections and render them instead of current templates. they would replace current templates tmHeader, tmStruct, tmObjApi, tmQueryApi, tmManagedObjApi.
here is a sample for single template with multiple sections.
http://play.golang.org/p/Q3NMOymzfT

**Comment by mijia** [comment]
Got it, make sense to me, will do this, :)

**Comment by mijia** [comment]
Hi @tarqe39 sorry for so late, have been kept busy for these days. I kinda commit the feature into master and now the template is supported. Please check the examples/custom.tmpl for example and the generated codes are listed in examples/custom.

Please let me know if the basic fragments or the template arguments are not enough for you requirements. :)

**Comment by tarqe39** [comment]
Haven't tried it yet, but I looked ath changes and example and it looks good :) thx
